name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      FLASK_KEY: ${{ secrets.FLASK_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GOOGLETTS_CREDENTAILS_BASE64: ${{ secrets.GOOGLETTS_CREDENTIALS_BASE64 }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt

      - name: Flask Application unittests
        working-directory: ./test/app
        env:
          GOOGLETTS_CREDENTIALS_BASE64: ${{ secrets.GOOGLETTS_CREDENTIALS_BASE64 }}
        run: python3 app.py